title: Rohit Menon
logo: assets/img/Headshot.jpg
description: Current MS Student in MIDS (Masters of Information and Data Science) at UC Berkeley
theme: jekyll-theme-minimal

# Navigation Links
nav_links:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about/"
  - title: "Resume"
    url: "/resume/"
  - title: "Projects"
    url: "/projects/"
  - title: "Contact"
    url: "/contact/"
